INSERT INTO films_rating (id, name)
SELECT 1, 'G' WHERE NOT EXISTS (SELECT 1 FROM films_rating WHERE id = 1)
UNION ALL
SELECT 2, 'PG' WHERE NOT EXISTS (SELECT 1 FROM films_rating WHERE id = 2)
UNION ALL
SELECT 3, 'PG-13' WHERE NOT EXISTS (SELECT 1 FROM films_rating WHERE id = 3)
UNION ALL
SELECT 4, 'R' WHERE NOT EXISTS (SELECT 1 FROM films_rating WHERE id = 4)
UNION ALL
SELECT 5, 'NC-17' WHERE NOT EXISTS (SELECT 1 FROM films_rating WHERE id = 5);

INSERT INTO genre (id, genre_name)
SELECT 1, 'Комедия' WHERE NOT EXISTS (SELECT 1 FROM genre WHERE id = 1)
UNION ALL
SELECT 2, 'Драма' WHERE NOT EXISTS (SELECT 1 FROM genre WHERE id = 2)
UNION ALL
SELECT 3, 'Мультфильм' WHERE NOT EXISTS (SELECT 1 FROM genre WHERE id = 3)
UNION ALL
SELECT 4, 'Триллер' WHERE NOT EXISTS (SELECT 1 FROM genre WHERE id = 4)
UNION ALL
SELECT 5, 'Документальный' WHERE NOT EXISTS (SELECT 1 FROM genre WHERE id = 5)
UNION ALL
SELECT 6, 'Боевик' WHERE NOT EXISTS (SELECT 1 FROM genre WHERE id = 6);
